// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCbxbMI-2rRgcJJlSlRwYoVSBn2FvMwJ1E',
    appId: '1:689603811376:web:66042446a2ab7d911a35f5',
    messagingSenderId: '689603811376',
    projectId: 'dormitory-management-sys-8e843',
    authDomain: 'dormitory-management-sys-8e843.firebaseapp.com',
    storageBucket: 'dormitory-management-sys-8e843.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAThQWlN1LOe9AZvyKk4N0Z9U6kDj_BdmU',
    appId: '1:689603811376:android:fee3cf28ad33b96c1a35f5',
    messagingSenderId: '689603811376',
    projectId: 'dormitory-management-sys-8e843',
    storageBucket: 'dormitory-management-sys-8e843.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBClDzAID2w_ylLKDiUe4ynq8fg_8-mZjk',
    appId: '1:689603811376:ios:5787b8f9ff15749e1a35f5',
    messagingSenderId: '689603811376',
    projectId: 'dormitory-management-sys-8e843',
    storageBucket: 'dormitory-management-sys-8e843.firebasestorage.app',
    iosBundleId: 'com.example.dormitoryApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBClDzAID2w_ylLKDiUe4ynq8fg_8-mZjk',
    appId: '1:689603811376:ios:5787b8f9ff15749e1a35f5',
    messagingSenderId: '689603811376',
    projectId: 'dormitory-management-sys-8e843',
    storageBucket: 'dormitory-management-sys-8e843.firebasestorage.app',
    iosBundleId: 'com.example.dormitoryApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCbxbMI-2rRgcJJlSlRwYoVSBn2FvMwJ1E',
    appId: '1:689603811376:web:c071b3b88243841f1a35f5',
    messagingSenderId: '689603811376',
    projectId: 'dormitory-management-sys-8e843',
    authDomain: 'dormitory-management-sys-8e843.firebaseapp.com',
    storageBucket: 'dormitory-management-sys-8e843.firebasestorage.app',
  );
}
